blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question or Chat
    url: https://github.com/v-gajjar/Minesweeper/discussions
    about: Use GitHub Discussions for general questions, ideas, or community talk.