name: 🧪 Build Checks

on:
  push:
    branches:
      - '**'
  pull_request:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4
        with:
          path: .
        
      - name: 📅 Set Today's Date (MM/DD/YYYY)
        id: date
        run: echo "today=$(date +'%m/%d/%Y')" >> "$GITHUB_OUTPUT"

      - name: 🟢 Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔧 Build App (Vite)
        run: npm run build

      - name: 🧪 Run Unit Tests (Vitest)
        run: npm run test

      - name: 🧪 Run ESLint
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          npx eslint src --ext .js,.jsx,.ts,.tsx --cache --quiet > eslint-report-$PR_NUMBER.txt || true

      - name: 🧪 Run Prettier (warn-only)
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          npx prettier --list-different . > prettier-report-$PR_NUMBER.txt || true
      
      - name: 🎨 Run Stylelint
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          npx stylelint "**/*.{css,scss}" > stylelint-report-$PR_NUMBER.txt || true

      - name: 📦 Upload Lint Reports
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports-pr-${{ github.event.pull_request.number }}
          path: |
            eslint-report-${{ github.event.pull_request.number }}.txt
            prettier-report-${{ github.event.pull_request.number }}.txt
            stylelint-report-${{ github.event.pull_request.number }}.txt