name: 🧪 PR Checks

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - main
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    outputs:
      today: ${{ steps.date.outputs.today }}
      node-version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: 📅 Set Today's Date (MM/DD/YYYY)
        id: date
        run: echo "today=$(date +'%m/%d/%Y')" >> "$GITHUB_OUTPUT"

      - name: 🟢 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📋 Set Node Version
        id: set-version
        run: echo "version='${{ matrix.node-version }}'" >> "$GITHUB_OUTPUT"

      - name: 📦 Install dependencies
        run: npm install

      - name: 🔧 Build App (Vite)
        run: npm run build

      - name: 🧪 Run Unit Tests (Vitest)
        run: npm run test

  comment-success:
    needs: build-lint-test
    runs-on: ubuntu-latest
    if: ${{ success() && github.event_name == 'pull_request_target' }}
    env:
      NODE_VERSION: '${{ needs.build-lint-test.outputs.node-version }}'
      TODAY: '${{ needs.build-lint-test.outputs.today }}'
    steps:
      - name: ✨ Comment Success with Blessing, Date, and Robot GIF
        uses: actions/github-script@v7
        with:
          script: |
            const baseRepo = context.payload.pull_request.base.repo;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: baseRepo.owner.login,
              repo: baseRepo.name,
              body: `✅ All checks passed on Node.js **${process.env.NODE_VERSION}**! 🎯 🤖 The bots have blessed your code on **${process.env.TODAY}** ✨ ![Blessed Robot](https://media.tenor.com/2roX3uxz_68AAAAC/cute-robot.gif)`
            });

  comment-failure:
    needs: build-lint-test
    runs-on: ubuntu-latest
    if: ${{ failure() && github.event_name == 'pull_request_target' }}
    env:
      TODAY: '${{ needs.build-lint-test.outputs.today }}'
    steps:
      - name: 💥 Comment Failure with Sad Robot
        uses: actions/github-script@v7
        with:
          script: |
            const baseRepo = context.payload.pull_request.base.repo;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: baseRepo.owner.login,
              repo: baseRepo.name,
              body: `❌ Tests or build failed on **${process.env.TODAY}**. 🐛🔥
              😢 The bots are sad. Please fix the issues! ![Sad Robot](https://media.tenor.com/oxT1qGgoAjwAAAAC/robot-sad.gif)`
            });