name: 🧪 PR Checks

on:
  push:
    branches:
      - '**'
  pull_request:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: 📅 Set Today's Date (MM/DD/YYYY)
        id: date
        run: echo "today=$(date +'%m/%d/%Y')" >> "$GITHUB_OUTPUT"

      - name: 🟢 Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔧 Build App (Vite)
        run: npm run build

      - name: 🧪 Run Unit Tests (Vitest)
        run: npm run test

      - name: 🧪 Run ESLint
        run: npx eslint . --ext .ts,.tsx,.js,.jsx

      - name: 🧪 Run Prettier
        run: npx prettier --check .